# Generated by Django 2.1.7 on 2019-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uplooaded_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Uploaded_images')),
            ],
        ),
    ]
